//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SI_ccp.BundleRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BundleRef.IBundlePlan")]
    public interface IBundlePlan {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBundlePlan/CreateBunldePlan", ReplyAction="http://tempuri.org/IBundlePlan/CreateBunldePlanResponse")]
        string CreateBunldePlan(string sUname, string sPwd, string sData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBundlePlan/CreateBunldePlan", ReplyAction="http://tempuri.org/IBundlePlan/CreateBunldePlanResponse")]
        System.Threading.Tasks.Task<string> CreateBunldePlanAsync(string sUname, string sPwd, string sData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBundlePlan/DeleteBunldePlan", ReplyAction="http://tempuri.org/IBundlePlan/DeleteBunldePlanResponse")]
        string DeleteBunldePlan(string sUname, string sPwd, string sData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBundlePlan/DeleteBunldePlan", ReplyAction="http://tempuri.org/IBundlePlan/DeleteBunldePlanResponse")]
        System.Threading.Tasks.Task<string> DeleteBunldePlanAsync(string sUname, string sPwd, string sData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBundlePlan/getbundleplan_details", ReplyAction="http://tempuri.org/IBundlePlan/getbundleplan_detailsResponse")]
        string getbundleplan_details(string sUname, string sPwd, string sData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBundlePlan/getbundleplan_details", ReplyAction="http://tempuri.org/IBundlePlan/getbundleplan_detailsResponse")]
        System.Threading.Tasks.Task<string> getbundleplan_detailsAsync(string sUname, string sPwd, string sData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBundlePlan/EditBunldePlan", ReplyAction="http://tempuri.org/IBundlePlan/EditBunldePlanResponse")]
        string EditBunldePlan(string sUname, string sPwd, string sData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBundlePlan/EditBunldePlan", ReplyAction="http://tempuri.org/IBundlePlan/EditBunldePlanResponse")]
        System.Threading.Tasks.Task<string> EditBunldePlanAsync(string sUname, string sPwd, string sData);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBundlePlanChannel : SI_ccp.BundleRef.IBundlePlan, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BundlePlanClient : System.ServiceModel.ClientBase<SI_ccp.BundleRef.IBundlePlan>, SI_ccp.BundleRef.IBundlePlan {
        
        public BundlePlanClient() {
        }
        
        public BundlePlanClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BundlePlanClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BundlePlanClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BundlePlanClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string CreateBunldePlan(string sUname, string sPwd, string sData) {
            return base.Channel.CreateBunldePlan(sUname, sPwd, sData);
        }
        
        public System.Threading.Tasks.Task<string> CreateBunldePlanAsync(string sUname, string sPwd, string sData) {
            return base.Channel.CreateBunldePlanAsync(sUname, sPwd, sData);
        }
        
        public string DeleteBunldePlan(string sUname, string sPwd, string sData) {
            return base.Channel.DeleteBunldePlan(sUname, sPwd, sData);
        }
        
        public System.Threading.Tasks.Task<string> DeleteBunldePlanAsync(string sUname, string sPwd, string sData) {
            return base.Channel.DeleteBunldePlanAsync(sUname, sPwd, sData);
        }
        
        public string getbundleplan_details(string sUname, string sPwd, string sData) {
            return base.Channel.getbundleplan_details(sUname, sPwd, sData);
        }
        
        public System.Threading.Tasks.Task<string> getbundleplan_detailsAsync(string sUname, string sPwd, string sData) {
            return base.Channel.getbundleplan_detailsAsync(sUname, sPwd, sData);
        }
        
        public string EditBunldePlan(string sUname, string sPwd, string sData) {
            return base.Channel.EditBunldePlan(sUname, sPwd, sData);
        }
        
        public System.Threading.Tasks.Task<string> EditBunldePlanAsync(string sUname, string sPwd, string sData) {
            return base.Channel.EditBunldePlanAsync(sUname, sPwd, sData);
        }
    }
}
